channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - pip=22.3.1
  - pandas
  - scipy
  - numpy
  - pip:
      - azure-identity==1.17.1
      - azure-storage-blob
      - azure-ai-ml==1.18.0
      - setuptools==65.5.1
      - wheel~=0.38.1
      - matplotlib~=3.5.0
      - psutil~=5.8.0
      - tqdm~=4.66.3
      - ipykernel~=6.20.2
      - azureml-core==1.56.0
      - azureml-defaults==1.56.0.post1
      - azureml-mlflow==1.56.0
      - azureml-telemetry==1.56.0
      - tensorboard~=2.16.0
      - tensorflow~=2.16.0
      - tensorflow-datasets~=4.9.0
      - onnxruntime-gpu~=1.15.0
      - debugpy~=1.6.3
      - cryptography>=41.0.4
      - idna>=3.7
      - librosa==0.10.2.post1
      - mltable
name: word-trigger-environment
