compute_cluster:
  name: word-trigger-cluster
  size: STANDARD_DS3_v2
  min_instances: 0
  max_instances: 2
  idle_time_before_scale_down: 120
  tier: Dedicated

deployment:
  version: v1.0
  instance_type: Standard_DS3_v2
  instance_count: 1
  default_environment: azureml:trigger-word-detection-environment:14
