$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: evaluate_model
display_name: Evaluate Model
version: 1
type: command

inputs:
  model_path:
    type: uri_folder
    description: Path to the MLflow model directory
  test_data:
    type: uri_folder
    description: Path to the folder containing test data (X_test.npy and y_test.npy)
  experiment_name:
    type: string
    default: "trigger-word-detection"
    description: Name of the MLflow experiment

outputs:
  output_metrics:
    type: uri_file
    description: Path to save the evaluation metrics JSON file

code: ../src/evaluation

environment: azureml:trigger-word-detection-environment:14

command: >-
  python evaluation.py 
  --model_path ${{inputs.model_path}} 
  --test_data ${{inputs.test_data}} 
  --output_metrics ${{outputs.output_metrics}}
  --experiment_name ${{inputs.experiment_name}}
